import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

// Fix for __dirname in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
// Cloud Run sets the PORT environment variable. Default to 8080 if not set.
const port = process.env.PORT || 8080;

// Serve static files from the 'dist' directory generated by Vite
app.use(express.static(path.join(__dirname, 'dist')));

// Handle SPA routing: return index.html for any unknown route
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

// Explicitly bind to 0.0.0.0 to ensure external access in containers
app.listen(port, '0.0.0.0', () => {
  console.log(`Server listening on port ${port}`);
});